export const mock = {
  restaurantName: 'burger tan kong',
  transactionId: 1,
  menus: [
    {
      name: 'french fried',
      quantity: 1,
      totalPrice: 99,
      special: '',
    },
    {
      name: 'brend285',
      quantity: 1,
      totalPrice: 285,
      special: '',
    },
    {
      name: 'เล้ง',
      quantity: 1,
      totalPrice: 60,
      special: 'ไม่เผ็ด',
    },
    {
      name: 'หมูย่าง',
      quantity: 1,
      totalPrice: 3000,
      special: 'สุกๆ',
    },
    {
      name: 'ไก่ย่าง',
      quantity: 1,
      totalPrice: 50,
      special: 'ไหม้ไหม้',
    },
    {
      name: 'เนื้อย่าง',
      quantity: 1,
      totalPrice: 30,
      special: 'ไม่ไหม้',
    },
    {
      name: 'หมูทอด',
      quantity: 1,
      totalPrice: 30,
      special: '',
    },
    {
      name: 'หมูแดดเดียว',
      quantity: 1,
      totalPrice: 30,
      special: '',
    },
    {
      name: 'เนื้อย่าง',
      quantity: 1,
      totalPrice: 30,
      special: 'ไม่ไหม้',
    },
    {
      name: 'หมูทอด',
      quantity: 1,
      totalPrice: 30,
      special: '',
    },
    {
      name: 'หมูแดดเดียว',
      quantity: 1,
      totalPrice: 30,
      special: '',
    },
  ],
  serviceCharge: 10,
  tax: 7,
  totalPrice: 117.7,
}
